SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `bancoHackaton` ;
USE `bancoHackaton` ;

CREATE TABLE IF NOT EXISTS `bancoHackaton`.`conta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `conta` VARCHAR(45) NOT NULL,
  `agencia` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `digitoAgencia` VARCHAR(45) NOT NULL,
  `digitoConta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `bancoHackaton`.`pessoa` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `conta_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pessoa_conta_idx` (`conta_id` ASC),
  CONSTRAINT `fk_pessoa_conta`
    FOREIGN KEY (`conta_id`)
    REFERENCES `bancoHackaton`.`conta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;